### ISSUE TITLE
Font CDN....

### ISSUE THREAD

**Issue by kaithar** [AndrewBelt/WiTeX#1]
Have you considered just throwing cloudflare or coralcdn in front of it?

**Comment by AndrewBelt** [comment]
Is it possible to offload the fonts entirely onto a CDN service? I'd prefer to not associate them with the current host.
Obviously HTTPS would be required for Wikipedia HTTPS pages.

**Comment by kaithar** [comment]
With those two, I don't think so :(  It might be possible to revert back to hosting on github though, if one of the two fixes the CORS issue you had.

**Comment by AndrewBelt** [comment]
Oh, that's a good idea. I'll see if those CDN services serve with the CORS header.

**Comment by AndrewBelt** [comment]
Fixed with fc422c46cfbe7e7e76d2595a38852f116e78d8b7
