### ISSUE TITLE
code/pre tags font size is too large

### ISSUE THREAD

**Issue by solson** [AndrewBelt/WiTeX#11]
See [here](https://en.wikipedia.org/wiki/C%2B%2B14#Standard_user-defined_literals) or my [screenshot](http://i.imgur.com/WR6p4jM.png) for example.

The inline `code` tags and block `pre` tags have very large fonts.

**Comment by AndrewBelt** [comment]
Fixed with e0ec0d99fb8bd8a7f6f52daf2786ba882733f3d9 by using Latin Modern Mono, which is correctly sized.
