### ISSUE TITLE
Search Bar invisibility

### ISSUE THREAD

**Issue by Marviel** [AndrewBelt/WiTeX#12]

**Comment by AndrewBelt** [comment]
I'm assuming you mean the Wikipedia search bar should auto-hide.
This has been requested, but I think Google, DuckDuckGo, etc are better, quicker portals to Wikipedia and do not clutter the reading interface.

**Comment by Marviel** [comment]
Fair enough; it's just an extra click to get to what I want. Unless I've
got a plugin, which I do.
