### ISSUE TITLE
Red links

### ISSUE THREAD

**Issue by qguv** [AndrewBelt/WiTeX#14]
On Wikipedia, so-called [red links](https://en.wikipedia.org/wiki/Wikipedia:Red_link) link to Wikipedia pages that have not yet been created. From the linked page:

> [Red links] indicate that a page will be created soon or that an article should be created for the topic because the subject is notable and verifiable. One study conducted in 2008 showed that red links helped Wikipedia grow. Follow-up work on this indicated that the creation of red links prevents new pages from being orphaned from the start.

For editors active in a particular topic, red links indicate which pages need to be created to bring colloquial readers up-to-speed with technical language in an article.

WiTeX unfortunately presents every link as a red link. This can be tested using [this page](https://en.wikipedia.org/wiki/Wikipedia:Most-wanted_articles), which has an introduction full of "blue" `a` links but otherwise chiefly red `a.new` links.

I love the WiTeX format, but can't help my visceral reaction to red links.

Would you be open to a PR causing`a.new` links to appear a different color than regular `a` links (but not green)? Better yet, would you be open to `a` links being some non-red color and `a.new` links remaining red?

**Comment by AndrewBelt** [comment]
I like the typographic style of medieval bibles and manuscripts, which use red to [highlight important text](http://www.educationscotland.gov.uk/Images/manuscripts1cistercianmissalparis%20L_tcm4-566176.jpg). I could make new links a distinguishably brighter red, whih I believe would solve the issue.

**Comment by qguv** [comment]
> I could make new links a distinguishably brighter red, whih I believe would solve the issue.

This would work, but it might make it difficult to distinguish the two. But to avoid a [bikeshed](http://white.bikeshed.com/), especially because red links are relatively uncommon, just pick the option you like and I'll submit a PR.
1. distinguishably brighter red
2. Teal (standard CSS `teal`) looks good and similar to the turquoise-teal used in some manuscripts.
3. External-link blue might also be a good choice, especially since it's already being used. There wouldn't be ambiguity, though, because external links use the external link icon.

I also experimented with the light violet/indigo and light green colors found in some manuscripts but couldn't get it right.

**Comment by AndrewBelt** [comment]
Fixed with e16cc088252c5023fecd89c0391f154a0efa054d
The color #e33 appears to read well without distractions in articles with occasional orphaned links. Thanks for the suggestion. Still welcome to more suggestions of color pairs for a/a.new.

**Comment by AndrewBelt** [comment]
Actually from a readability perspective, new links have no purpose at all, so I've made them black in 2ada10aeff8cd73f43947d731b21b3598404eb2d. (If you edit Wikipedia, I recommend not using WiTeX to make sure your edits display correctly for the majority of Wikipedia users.)

**Comment by qguv** [comment]
I really like this solution, thanks.
