### ISSUE TITLE
Change color of equations?

### ISSUE THREAD

**Issue by lizard-heart** [AndrewBelt/WiTeX#20]
Hi, I've been messing around with the css because I've been trying to make a dark mode. The only problem is that the equations remain black. Is it possible to change the color of LaTeX equations with the css?

**Comment by AndrewBelt** [comment]
You can use `filter: invert(100%)` for formulas if you want them to have a white foreground and black background.

**Comment by lizard-heart** [comment]
Cool, thanks, that's really useful!
