### ISSUE TITLE
What license is this under?

### ISSUE THREAD

**Issue by sharvilshah** [AndrewBelt/WiTeX#4]
Great work.

You can use Github's [Choose-a-license](http://choosealicense.com/). If you do choose, can you please
add  `LICENSE` file or include which license you are releasing this in the `README`.

Please note, that you are [under no obligation to choose a license](http://choosealicense.com/no-license/).

**Comment by sharvilshah** [comment]
Sorry, didn't see the public domain comment in the stylesheet.

**Comment by AndrewBelt** [comment]
I should copy it to a LICENSE.md file at the root.
